<a href="https://colab.research.google.com/github/rodriguesrleonardo/rodriguesrleonardo/blob/main/Extra%C3%A7%C3%A3o_de_dados_SPED_ICMS_IPI_Vers%C3%A3o_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Obs.: Precisa alimentar a pasta SPED. Ideal sempre apagar tudo e criar uma pasta nova com o mesmo nome SPED e fazer upload dos arquivos de um determinado período

# 1º Bibliotecas necessárias

In [2]:
!pip install pandas openpyxl xlsxwriter -q

# 2º Importações e configurações

In [30]:
import os
import pandas as pd
from datetime import datetime

PASTA_SPED = "/content/SPED"

from datetime import datetime

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

ARQUIVO_EXCEL = f"/content/SPED/RESULTADOS/Consolidado_SPED_{timestamp}.xlsx"
ARQUIVO_CFOP = f"/content/SPED/RESULTADOS/CFOP_DETALHADO_{timestamp}.csv"

# 3º Funções Auxiliares

In [4]:
def to_float(valor):
    if valor is None:
        return 0.0

    valor = str(valor).strip()

    if valor == "":
        return 0.0

    try:
        return float(valor.replace(".", "").replace(",", "."))
    except:
        return 0.0


def obter_raiz_cnpj(cnpj):
    return str(cnpj)[:8]


def obter_periodo(data_ini):
    if len(data_ini) != 8:
        return ""

    return f"{data_ini[4:8]}-{data_ini[2:4]}"


def tipo_cfop(cfop):
    cfop = str(cfop)

    if cfop.startswith("1"):
        return "Entrada Estadual"

    if cfop.startswith("2"):
        return "Entrada Interestadual"

    if cfop.startswith("3"):
        return "Importação"

    if cfop.startswith("5"):
        return "Saída Estadual"

    if cfop.startswith("6"):
        return "Saída Interestadual"

    if cfop.startswith("7"):
        return "Exportação"

    return "Não Identificado"

# 4º Estrutura de dados

In [5]:
empresas = []
cfop_detalhado = []
apuracoes = []
ajustes = []
obrigacoes = []

# 5º Leitura dos arquivos SPED

In [6]:
arquivos_txt = [
    arq
    for arq in os.listdir(PASTA_SPED)
    if arq.lower().endswith(".txt")
]

print(f"{len(arquivos_txt)} arquivos encontrados.")

187 arquivos encontrados.

# 6º Processamento de dados

In [7]:
for arquivo in arquivos_txt:

    caminho = os.path.join(PASTA_SPED, arquivo)

    print(f"Processando {arquivo}")

    empresa = {
        "RAIZ_CNPJ": "",
        "CNPJ": "",
        "IE": "",
        "RAZAO_SOCIAL": "",
        "UF": "",
        "PERIODO": "",
        "ARQUIVO": arquivo
    }

    ultimo_num_doc = ""
    ultima_chave = ""

    with open(caminho, "r", encoding="latin-1") as f:

        for linha in f:

            linha = linha.strip()

            if not linha:
                continue

            campos = linha.split("|")

            if len(campos) < 2:
                continue

            registro = campos[1]

            # -----------------------------------
            # REGISTRO 0000
            # -----------------------------------

            if registro == "0000":

                data_ini = campos[4]
                data_fim = campos[5]

                empresa["CNPJ"] = campos[7]
                empresa["RAIZ_CNPJ"] = obter_raiz_cnpj(campos[7])
                empresa["RAZAO_SOCIAL"] = campos[6]
                empresa["UF"] = campos[9]
                empresa["IE"] = campos[10]
                empresa["PERIODO"] = obter_periodo(data_ini)

                empresas.append({
                    **empresa,
                    "DATA_INICIAL": data_ini,
                    "DATA_FINAL": data_fim
                })

            # -----------------------------------
            # C100
            # -----------------------------------

            elif registro == "C100":

                ultimo_num_doc = campos[8] if len(campos) > 8 else ""

                ultima_chave = campos[9] if len(campos) > 9 else ""

            # -----------------------------------
            # C190
            # -----------------------------------

            elif registro == "C190":

                cfop_detalhado.append({

                    **empresa,

                    "TIPO_OPERACAO": tipo_cfop(campos[3]),

                    "NUM_DOC": ultimo_num_doc,
                    "CHV_NFE": ultima_chave,

                    "CST": campos[2],
                    "CFOP": campos[3],
                    "ALIQ_ICMS": to_float(campos[4]),

                    "VL_OPR": to_float(campos[5]),
                    "VL_BC_ICMS": to_float(campos[6]),
                    "VL_ICMS": to_float(campos[7]),
                    "VL_BC_ST": to_float(campos[8]),
                    "VL_ICMS_ST": to_float(campos[9]),
                    "VL_RED_BC": to_float(campos[10])
                })

            # -----------------------------------
            # E110
            # -----------------------------------

            elif registro == "E110":

                apuracoes.append({

                    **empresa,

                    "VL_TOT_DEBITOS": to_float(campos[2]),
                    "VL_AJ_DEBITOS": to_float(campos[3]),
                    "VL_TOT_AJ_DEBITOS": to_float(campos[4]),
                    "VL_ESTORNOS_CRED": to_float(campos[5]),
                    "VL_TOT_CREDITOS": to_float(campos[6]),
                    "VL_AJ_CREDITOS": to_float(campos[7]),
                    "VL_TOT_AJ_CREDITOS": to_float(campos[8]),
                    "VL_ESTORNOS_DEB": to_float(campos[9]),
                    "VL_SLD_CREDOR_ANT": to_float(campos[10]),
                    "VL_SLD_APURADO": to_float(campos[11]),
                    "VL_TOT_DED": to_float(campos[12]),
                    "VL_ICMS_RECOLHER": to_float(campos[13]),
                    "VL_SLD_CREDOR_TRANSPORTAR": to_float(campos[14])
                })

            # -----------------------------------
            # E111
            # -----------------------------------

            elif registro == "E111":

                ajustes.append({

                    **empresa,

                    "COD_AJUSTE": campos[2],
                    "DESCRICAO": campos[3],
                    "VALOR": to_float(campos[4])
                })

            # -----------------------------------
            # E116
            # -----------------------------------

            elif registro == "E116":

                obrigacoes.append({

                    **empresa,

                    "COD_ORIGEM": campos[2],
                    "VALOR": to_float(campos[3]),
                    "VENCIMENTO": campos[4],
                    "COD_RECEITA": campos[5],
                    "DESCRICAO": campos[10] if len(campos) > 10 else ""
                })

Processando 17625216001036-796186792116-20260401-20260430-0-983574799314D4D91B0BE903E518C71671AE26C7-SPED-EFD.txt
Processando 17625216002512-796248079116-20260401-20260430-0-D592DE4CF055225455AB1A106206D1E3F9265673-SPED-EFD.txt
Processando 17625216000307-796186844116-20260401-20260430-0-13BAD98D76303B4C652312C365981784675F8AAF-SPED-EFD.txt
Processando 27197888015930-795598280110-20260401-20260430-0-CD20A726FDCA96E7DFEE50EB8E2075BD8F190085-SPED-EFD.txt
Processando 27197888027270-054691966-20260401-20260430-0-A86D28E342780FAF0CC5EDA380B9F04CA3549548-SPED-EFD.txt
Processando 17625216000226-796186817113-20260401-20260430-0-EE105671F46070CB1DA35E45A454E95951CC385A-SPED-EFD.txt
Processando 27197888018955-0628832431288-20260401-20260430-0-353E76302AF060F2E6E370CA8938145E1625CBFC-SPED-EFD.txt
Processando 27197888022472-795884548110-20260401-20260430-0-3C197BEF95BE4D9909A81E47AA8448B23E3A9BEC-SPED-EFD.txt
Processando 27197888017207-0738333402180-20260401-20260430-0-3D539483A2C6C04252A58A232967A41B3D186E18-SPED-EFD.txt
Processando 27197888025064-12124236-20260401-20260430-0-3EBD019B95EF1432CDBF2B8B790C804511C96D7A-SPED-EFD.txt
Processando 27197888025900-200450946-20260401-20260430-0-2E8EAE8E8233C734748FA67DFE9567F01B144D03-SPED-EFD.txt
Processando 27197888017479-86965143-20260401-20260430-0-F4AED582BA06445A647EF6D56F0037FAA61FE461-SPED-EFD.txt
Processando 27197888000665-022034056-20260401-20260430-0-DDE7B27BFEBEF18D0538F50311757C1BB2A305BF-SPED-EFD.txt
Processando 17625216000811-796186765113-20260401-20260430-0-ECFD154F69882AAEC53288BFCCC69D0368215152-SPED-EFD.txt
Processando 17625216007824-153671300117-20260401-20260430-0-3D299823F07F6B5248F9B88B3D176CC5280B926D-SPED-EFD.txt
Processando 17625216003241-795516089111-20260401-20260430-0-685884AE0FF66839609D4F35092140F5DC517F66-SPED-EFD.txt
Processando 27197888028160-154707948111-20260401-20260430-0-20D7CF77279848AACAE55A94A0A9F1D64793D875-SPED-EFD.txt
Processando 27197888025650-261899651-20260401-20260430-0-4A07AC53AF06D6C613B613A24F3B61AEE56A3F61-SPED-EFD.txt
Processando 27197888026540-084165553-20260401-20260430-0-F37BF1A07223F2826DF29F1D25BDEB8E8310B92D-SPED-EFD.txt
Processando 27197888015344-204062926-20260401-20260430-0-01A5602D029D92B27CAA6D11E270D30323BC95D3-SPED-EFD.txt
Processando 17625216006267-072208988-20260401-20260430-0-F925D7FEA1D98ED35DC1CA16ABEC34570D1559B4-SPED-EFD.txt
Processando 17625216006186-072210567-20260401-20260430-0-AB0C37B9A6DFBEB3A50B9438A1A9463B1C1252AD-SPED-EFD.txt
Processando 27197888024920-0963863770-20260401-20260430-0-11E68D970E4CDAA9CDBDD35FCBD121A92440971D-SPED-EFD.txt
Processando 27197888017630-796361479116-20260401-20260430-0-1C40216202C35CCB0C4D522CFB303771B60323D8-SPED-EFD.txt
Processando 27197888016316-795599151111-20260401-20260430-0-11BC3FCCF2D24F6D476033ABB5FD2048117E2AE2-SPED-EFD.txt
Processando 27197888024254-0963797751-20260401-20260430-0-B41531702A61A96B7732AC51EFE5A8AFDA663E08-SPED-EFD.txt
Processando 17625216005538-194181342-20260401-20260430-0-67858ECBC2CDC8E7CC64390C063A97AB4F701F54-SPED-EFD.txt
Processando 27197888009700-153091622-20260401-20260430-1-E3D55AF5A0CAA5180BC31B19AF06C8A3F5A73305-SPED-EFD.txt
Processando 17625216003918-796365720112-20260401-20260430-0-F1E36D4E920811A7FFB1CDF94F1C5E972B850CD4-SPED-EFD.txt
Processando 17625216001460-796186862118-20260401-20260430-0-F74C3FFBBB574344E250E9929417AABB6FE81F0A-SPED-EFD.txt
Processando 27197888016073-795598299118-20260401-20260430-0-F596DC203C0DE4BDB99D7C553606E7C6C6113677-SPED-EFD.txt
Processando 27197888023606-0628832431938-20260401-20260430-0-79AE6A54601315D9E41EF05CF53A3F3FEB3B8451-SPED-EFD.txt
Processando 27197888019765-796387645111-20260401-20260430-0-4D48CE5F17E845D36AD09909E67D04635EC05C60-SPED-EFD.txt
Processando 17625216004647-258663227-20260401-20260430-0-D9710FF6C054EFCD392A6E7F1DD63B09F328A63D-SPED-EFD.txt
Processando 27197888019170-796387584110-20260401-20260430-0-20A96E0A43A62605195D09595696D935CFCB86A9-SPED-EFD.txt
Processando 27197888017550-796361460119-20260401-20260430-0-618E77D15CAB5A71A2BF13944CA1F9B2D7B77CB4-SPED-EFD.txt
Processando 17625216005880-054691850-20260401-20260430-0-3589617B06A4AFD91FACEE5685A47D9B3E4A4200-SPED-EFD.txt
Processando 27197888023282-11204120-20260401-20260430-0-34A7F2FB5C61B523A140931E5B72056DB2CB63FD-SPED-EFD.txt
Processando 27197888011942-067304028-20260401-20260430-0-0DCCEC844D53A527D80BB6A8ECB0A28B85D267FD-SPED-EFD.txt
Processando 27197888024335-0963797786-20260401-20260430-0-BBBFE5F772336D174E4C36F9DFB5D22E933EB9A4-SPED-EFD.txt
Processando 17625216007409-9111127600-20260401-20260430-0-CAF9F72A8D84F06C00865DDC16994E50C2AF54E2-SPED-EFD.txt
Processando 17625216006852-0050102330263-20260401-20260430-1-CA172FFED5284E1BF440384C97E69DA7F93AA712-SPED-EFD.txt
Processando 27197888025811-12610998-20260401-20260430-0-C9F63DADD55DE4269F0EE9C0947BDFD606536D8D-SPED-EFD.txt
Processando 27197888022391-795884539119-20260401-20260430-0-CEE3D091003210F7F0B5B310E28F7B1CF1BB1AA8-SPED-EFD.txt
Processando 27197888024416-061307696-20260401-20260430-0-D562BE9EB71DEA75E7B9C1FF0E911439FB2968D3-SPED-EFD.txt
Processando 27197888021310-87093263-20260401-20260430-0-24578768F4F4069F153F073E111DF6D8579590F2-SPED-EFD.txt
Processando 17625216007743-153671294117-20260401-20260430-0-22CD20FFC9BE82308FF4D99A0EC53AC0078B269A-SPED-EFD.txt
Processando 17625216006690-0050102330000-20260401-20260430-0-BA653F1FB45CD325465A5602548F0002569C2986-SPED-EFD.txt
Processando 17625216007905-126392064-20260401-20260430-0-78684212AC398C3B83C592D39890D4B9ECF8048C-SPED-EFD.txt
Processando 27197888027350-15101911-20260401-20260430-0-C9A1814C88155BAAC2D13B401886A62A4D4CF519-SPED-EFD.txt
Processando 27197888009883-81056334-20260401-20260430-0-BCEE2C0158E842C078F3CE2C4C48EA71C850AB78-SPED-EFD.txt
Processando 27197888023797-205219160-20260401-20260430-0-EA32C72A850B121D110459D38F147CC6F6AE21C6-SPED-EFD.txt
Processando 27197888026460-0817714300239-20260401-20260430-0-66DC6F6B27938FC0335B9B4E9FB55AEAB1F2C62C-SPED-EFD.txt
Processando 17625216005295-0963858327-20260401-20260430-0-E610CF656C514283A96D514D08B6570B04F8BC5D-SPED-EFD.txt
Processando 17625216005961-054691885-20260401-20260430-0-6EB131FD26D623AE0DF5FAD4F84CAF5F15DB8013-SPED-EFD.txt
Processando 27197888017800-0738333402342-20260401-20260430-0-7496EB33D85BA992D2DD7F99B1E1B130F130D7AA-SPED-EFD.txt
Processando 27197888024092-0963797913-20260401-20260430-0-07716CE740983DFB1A8BDB85E6F7EA920B3BF72D-SPED-EFD.txt
Processando 27197888007597-336812202117-20260401-20260430-0-1F1438703666FD732B9F06950E48531257FD3E2B-SPED-EFD.txt
Processando 27197888026621-132247020110-20260401-20260430-0-686903B7F90CB010C059E6B6532C300113FED814-SPED-EFD.txt
Processando 17625216003756-796365702110-20260401-20260430-0-2FC85D9B0079393E081D51C7A3865935FB652C71-SPED-EFD.txt
Processando 17625216000145-796159410113-20260401-20260430-0-49F2804D0E9FD6DEA04312E0A12C0A4E64F455B1-SPED-EFD.txt
Processando 27197888003923-336481562112-20260401-20260430-0-8AC19DCFABE7BB66C6DD9344D3B0CF67C43C0EFF-SPED-EFD.txt
Processando 27197888003680-75866577-20260401-20260430-0-B193432E07BE5643100DE3C77DFC162DB62D2537-SPED-EFD.txt
Processando 27197888027601-15429313-20260401-20260430-0-4EA773E8F25BB82B5449E21FD00591ACCDF597F0-SPED-EFD.txt
Processando 27197888004300-0738333400722-20260401-20260430-0-26A7183EFC010207A66EA159F34DBFA913EA903E-SPED-EFD.txt
Processando 17625216004132-796365749114-20260401-20260430-0-EA472BAC5BB257001DE76AAA577D2DCD3C2F7252-SPED-EFD.txt
Processando 27197888016740-86976528-20260401-20260430-0-B4668113D0862B4A4977B29961FC72C77181C510-SPED-EFD.txt
Processando 17625216007662-9112644552-20260401-20260430-0-D9BE71C8107611CCD87AF67FC829C385437FB96A-SPED-EFD.txt
Processando 27197888023878-260236918-20260401-20260430-0-0CED2E37759FAEACD5414529E32E0F3FD26D107B-SPED-EFD.txt
Processando 27197888018289-154954330-20260401-20260430-0-0AC8F0CF53142E36F4E1BADEA5BCFEE24C03E7DF-SPED-EFD.txt
Processando 17625216004809-1530196210-20260401-20260430-0-9F3287332F3B55E63EFF776C944B320C36830229-SPED-EFD.txt
Processando 27197888022200-795884520111-20260401-20260430-0-5B4F4CE8C300441E7A3A9A1821028FFC128A4EA7-SPED-EFD.txt
Processando 17625216005104-0963858319-20260401-20260430-0-A3E3F44DD1B099EFC49E0E406CDF1FE78D0AAC3A-SPED-EFD.txt
Processando 27197888026117-084002220-20260401-20260430-0-E8ECBF125CB94DBB85E8C961F4E21E52B273A519-SPED-EFD.txt
Processando 17625216001621-796247978115-20260401-20260430-0-9D597813D37EDC173CA871F93CC464C4F43CC0D8-SPED-EFD.txt
Processando 27197888003842-336481553111-20260401-20260430-0-BD66DC3DFCD1C2D2E26DA97D91475CAD37571F16-SPED-EFD.txt
Processando 27197888028080-0817714300310-20260401-20260430-0-E469E0B2ECBF1A084FB579FCA1E7C44A15F346B4-SPED-EFD.txt
Processando 62548367001254-156698120111-20260401-20260430-0-7FE6660A8106AA468C6F8DB67917223298AAF6F2-SPED-EFD.txt
Processando 27197888003761-75866526-20260401-20260430-0-98BDAC4555FFDFFF051B8F7E2B63EFBCEE103228-SPED-EFD.txt
Processando 27197888027199-054691931-20260401-20260430-1-E0CDDE7E9D77954D10BA9DEEA94AAB87A7C7A713-SPED-EFD.txt
Processando 17625216005619-194280801-20260401-20260430-0-056EF9E678BE87D544766E6E0563FC150840EB3C-SPED-EFD.txt
Processando 27197888021581-106733699-20260401-20260430-0-0FBEBD72BE878272E1D8115B3C5AA01357448973-SPED-EFD.txt
Processando 27197888012086-204038065-20260401-20260430-0-92B259F7CE5BD3BEE2ED3392A0544E46067978C5-SPED-EFD.txt
Processando 27197888024769-127153972117-20260401-20260430-0-D4A1DF6E6FF0835779FC28C1957C4FB643F3866C-SPED-EFD.txt
Processando 17625216007310-9111127104-20260401-20260430-0-57C7B596D57D3FF68A25E2B2F8C8C73CFBC41534-SPED-EFD.txt
Processando 27197888024173-0963797778-20260401-20260430-0-E081A0569EEDC3872327764E0A279C39CA27F76D-SPED-EFD.txt
Processando 27197888014291-0738333401370-20260401-20260430-0-57CE6803FDF982FEDE50649B612EDEC6BA88A422-SPED-EFD.txt
Processando 27197888014100-056848030-20260401-20260430-0-704E99EFBDD1AFB2BC4D47CFA90ACC0E12F3A446-SPED-EFD.txt
Processando 17625216001702-796247987116-20260401-20260430-0-A05E1FC8222BD30DCAAE0F98A233194D8E8B4C4F-SPED-EFD.txt
Processando 17625216006771-0050102330182-20260401-20260430-0-5865D3252F4540B4382F3E01EF475925E604C35B-SPED-EFD.txt
Processando 17625216003322-795516098112-20260401-20260430-0-7CAF261AD6D7B9122FCC86A455D4963F3BF69B52-SPED-EFD.txt
Processando 17625216004213-796402644116-20260401-20260430-0-5E3057266CDE2B4154E870152C80EB300809D43C-SPED-EFD.txt
Processando 17625216004566-155896695-20260401-20260430-0-FACA75F420A90F3F46ED3775FC67BEB7A6F34DBD-SPED-EFD.txt
Processando 17625216004051-796365730117-20260401-20260430-0-02F2FB53CC8D0E1051B56A8569CC13090DDACEC1-SPED-EFD.txt
Processando 17625216006429-206720831-20260401-20260430-0-254AB37BBC688AAFC364B0A09D1E42ABCDDEABFD-SPED-EFD.txt
Processando 17625216002199-796248023111-20260401-20260430-0-496CE9ADCC60BE609F6C4DBD46AD3483A3CC1301-SPED-EFD.txt
Processando 27197888027784-154195111112-20260401-20260430-0-277278A1E588BD1EBDDBEC0C5800DDCE49506901-SPED-EFD.txt
Processando 17625216003675-796365697114-20260401-20260430-0-25C32A34F9B2542449F6E06B050D2E648EC6272C-SPED-EFD.txt
Processando 17625216000650-796186880110-20260401-20260430-0-48F5163E2158F35BACD9D5B87BCBE57D07077955-SPED-EFD.txt
Processando 62548367001173-151778729115-20260401-20260430-0-3807E3182E1D03EBB8D2CDAE5127EC015590BEFB-SPED-EFD.txt
Processando 27197888019250-796387618119-20260401-20260430-0-C571F807591B1217AD0EC277B9A6CA13D215D899-SPED-EFD.txt
Processando 27197888016820-86976501-20260401-20260430-0-9CD4852CFBDF0B9FC3DAF7F4786E93C679E3FBC9-SPED-EFD.txt
Processando 17625216004485-155896709-20260401-20260430-0-A83D9BAC254C5CE1C36512C01C38060652BC6608-SPED-EFD.txt
Processando 27197888027946-154195120113-20260401-20260430-0-2DB4B0198E468CFB88F6D5F7DB09D17E981A269E-SPED-EFD.txt
Processando 27197888025498-0628832432357-20260401-20260430-0-B7A78427F725D498098D27DFED8377A6D2B4323F-SPED-EFD.txt
Processando 17625216007239-9110989625-20260401-20260430-0-7AB0AA674C1D8AC49168E19C855DCCC8F13F055A-SPED-EFD.txt
Processando 27197888007325-034443410-20260401-20260430-0-F0380F847003D48FABFE4A685320EE096CFABD58-SPED-EFD.txt
Processando 27197888027008-14206230-20260401-20260430-0-69413CAE1E68348837CEB124CD7906742B59CB55-SPED-EFD.txt
Processando 27197888023525-0628832431857-20260401-20260430-0-F1844F6391F9198FA8D45238B4BF430F54B9DDC9-SPED-EFD.txt
Processando 27197888027431-151778756118-20260401-20260430-0-772F54B2C36B1D54F65BA0B907344A4EF33352DC-SPED-EFD.txt
Processando 27197888019412-140103664117-20260401-20260430-0-78FC3AE38605693E344F498A9011618A3DE137E2-SPED-EFD.txt
Processando 27197888022715-796664347113-20260401-20260430-0-696D9C5C26E5672DF5FA20066BCFB4CDA9D27998-SPED-EFD.txt
Processando 17625216004302-155896717-20260401-20260430-0-A9FE28AF1A8F1E19759D21CCD38EC2B74FFA5E77-SPED-EFD.txt
Processando 17625216007581-152870489112-20260401-20260430-0-96151DD962FB1E17EA64BEB1F02AE45323A3D1E1-SPED-EFD.txt
Processando 17625216006348-206720823-20260401-20260430-0-3AC0E1C27AD1FEE882E862264FD91E18B23B5091-SPED-EFD.txt
Processando 27197888000584-021746184-20260401-20260430-0-6FC3305349E0585DDBA2CADAE282FA29CB8B6A7D-SPED-EFD.txt
Processando 17625216000579-796186853117-20260401-20260430-0-87A1F6E10775A857BA20AECE7C936F81CAD1702E-SPED-EFD.txt
Processando 27197888026702-14206205-20260401-20260430-0-29387C9F45DFAF5233DF3A2490A25AC3EB9A0179-SPED-EFD.txt
Processando 17625216006003-072210540-20260401-20260430-0-81C51D780D1793FFA321BB6248AC2B634E12A451-SPED-EFD.txt
Processando 27197888019684-796387636110-20260401-20260430-0-6445163CE1E519E526565A7C1366CA3548202242-SPED-EFD.txt
Processando 17625216000900-796186774114-20260401-20260430-0-112D67EA4A766BB79E7F0C2221C66B8EB5BC031C-SPED-EFD.txt
Processando 27197888026893-14206213-20260401-20260430-0-DEE044ED49DCD1CCDBE09A2BFB7902BFB8716B0F-SPED-EFD.txt
Processando 27197888017711-0738333402261-20260401-20260430-0-2A88D056BDD9B0DD62DE2681756AC533143EFCFA-SPED-EFD.txt
Processando 27197888025730-127752245119-20260401-20260430-0-62EB0FAC20D561EAD7FA97B21FF2BA4D1110657A-SPED-EFD.txt
Processando 17625216004990-796934585118-20260401-20260430-0-90879C26483B1CED81C0F34B65D1284C9BA263E0-SPED-EFD.txt
Processando 17625216007158-0833488900392-20260401-20260430-0-13FDDB6280D4A129660DE2B45E4E17E3ACC962D3-SPED-EFD.txt
Processando 27197888011357-105732990-20260401-20260430-0-CBA0C4FE6D1E8C7068DC36F17F79613E0B27512D-SPED-EFD.txt
Processando 17625216003403-795516103119-20260401-20260430-0-CBDDC36E75B3BF714DE19BC39233E913988026D1-SPED-EFD.txt
Processando 27197888004652-77129855-20260401-20260430-0-DBCF0CD333D0C00FF8F30FF1D592D2BCE7E45726-SPED-EFD.txt
Processando 17625216007077-0833488900201-20260401-20260430-0-951B001E2280F9940C2C1616ADD51A71FBDBEE69-SPED-EFD.txt
Processando 27197888014534-0738333401613-20260401-20260430-0-82B3F35FE8134E420F3F988E694B606B7092A0AE-SPED-EFD.txt
Processando 27197888025307-0628832432276-20260401-20260430-0-1CCA73E3B177D8F0DF2AE2EBEEEF6632F38F0C34-SPED-EFD.txt
Processando 27197888028241-16159379-20260401-20260430-0-BE4FA942F0C059A5411F92672A4D38B62FAE90A7-SPED-EFD.txt
Processando 17625216005708-054691842-20260401-20260430-0-F57F3E44CB8EF2392AB2E4CCC9EA353A5A902DD2-SPED-EFD.txt
Processando 27197888018602-87046591-20260401-20260430-0-033342B4E364A929B6652ACF2840A603CF429FA6-SPED-EFD.txt
Processando 27197888019099-0628832431369-20260401-20260430-0-CAC1C6354607A94814D164C92B7B392BE35DA503-SPED-EFD.txt
Processando 62548367000100-78106271-20260401-20260430-0-9FA3A755623960FE6F8E4597AA835CB5BF9CA8C2-SPED-EFD.txt
Processando 27197888019501-140103673118-20260401-20260430-0-5BB7F7E657E7AC0967809EDAA60FFABBF1174292-SPED-EFD.txt
Processando 17625216003160-796248130110-20260401-20260430-0-04D630605D20625ACE255928A2ECE37374A5156E-SPED-EFD.txt
Processando 27197888010709-336962729113-20260401-20260430-0-5AEC125ACA648F0D3BD6987463CA9EBA5743F0E9-SPED-EFD.txt
Processando 27197888026974-14206221-20260401-20260430-0-22BB82EBE19F5809BA9DAD4E40BDBF15D868D3AB-SPED-EFD.txt
Processando 62548367001335-0847310000146-20260401-20260430-0-82CDA61BD390A0CC67CEF09E2362D79D3A1BAB70-SPED-EFD.txt
Processando 27197888014453-0738333401532-20260401-20260430-0-F43348677A2B4D8C2AA04680426581222432D713-SPED-EFD.txt
Processando 27197888012248-796192357116-20260401-20260430-0-29F41EBB68F7EC42815D926329708309160FFC78-SPED-EFD.txt
Processando 27197888024505-061307483-20260401-20260430-0-129BFCD58BCE34E27745C6C240000FF7A2DB6F7E-SPED-EFD.txt
Processando 27197888023444-0628832431776-20260401-20260430-0-C0E0CC8A2175A943E9BE0044529968AACB383077-SPED-EFD.txt
Processando 17625216001974-796248005110-20260401-20260430-0-E35BCF2B03BB62EB87A0FFB46B339371BE2C4AA0-SPED-EFD.txt
Processando 17625216003080-796248120116-20260401-20260430-0-36B3B405FA8AE4CBB5AC8868B3269C3E44164CEF-SPED-EFD.txt
Processando 17625216005376-0963858351-20260401-20260430-0-ECFCA81C95764FEDA2446F548767BF66E3413892-SPED-EFD.txt
Processando 17625216005457-194181234-20260401-20260430-0-63A90189A586A9FA0807E7647E262AE5F66A31F8-SPED-EFD.txt
Processando 27197888012167-0738333401290-20260401-20260430-0-C43034B5EA8079734A4DE9B650EB255D433E8FAB-SPED-EFD.txt
Processando 27197888026389-241157072-20260401-20260430-0-A48C3396A4B6CD32BBBDF52149C240269FD9D8B8-SPED-EFD.txt
Processando 17625216006500-206720840-20260401-20260430-0-AAA02FB1313D6C49D846838F8BC4AD15296A277C-SPED-EFD.txt
Processando 27197888027512-9112288403-20260401-20260430-1-59A770A14DB67047FA514A8025AAEA57BFC28D89-SPED-EFD.txt
Processando 17625216005023-260236888-20260401-20260430-0-48DFBA6A7EABA9DE8B7AFA3818126F296BAED262-SPED-EFD.txt
Processando 27197888022120-795884510117-20260401-20260430-0-164B5F12ECEED70E7C1A57F51A295FBBDB54111B-SPED-EFD.txt
Processando 17625216008049-126392145-20260401-20260430-0-A907F632497AD01955588F79D4ECB081CD3F3152-SPED-EFD.txt
Processando 17625216004728-258678151-20260401-20260430-0-92C1C402DC11FF03F6ED542AEF0DB9220688CABD-SPED-EFD.txt
Processando 27197888016235-795598313115-20260401-20260430-0-D5A790C151142CFD2ACCBC4052A618F346CB6519-SPED-EFD.txt
Processando 27197888016405-795599160112-20260401-20260430-0-E970B47B072253EB5D28B1283FC91D3B0C2EC07A-SPED-EFD.txt
Processando 17625216002008-796248014110-20260401-20260430-0-53FDE18443BE177C080692C06FFC9FC01A37EB7E-SPED-EFD.txt
Processando 27197888028322-132266300-20260401-20260430-0-377EDF98B7E0B82B5D1276FEBCF99D4E31856EF3-SPED-EFD.txt
Processando 17625216006933-0833488900120-20260401-20260430-0-5A62DC6A0D3739EF84582B8A696B6825CA98D435-SPED-EFD.txt
Processando 27197888018017-0738333402504-20260401-20260430-0-6C63CB475BB1F33271C0C4D61781C5342E1CAD10-SPED-EFD.txt
Processando 27197888007406-149659104110-20260401-20260430-0-1F66EB0803193208B65A3B7D37A0EBBF5F65E0A3-SPED-EFD.txt
Processando 27197888026206-12728360-20260401-20260430-0-DFFA2529804DD18F44BEB2E103D54125C0810A9C-SPED-EFD.txt
Processando 27197888024688-061308455-20260401-20260430-0-289C1021574BEB2F509072D6CBCC7F5A05216676-SPED-EFD.txt
Processando 27197888014968-0738333402008-20260401-20260430-0-2153E50B15EA3E4E6ED69C7962413C93568A113C-SPED-EFD.txt
Processando 17625216003837-796365711111-20260401-20260430-0-D37905E5B89C35595276A19DD2DC80414718AE23-SPED-EFD.txt
Processando 17625216001893-796247996117-20260401-20260430-0-B08AD077A49B0E532FAEB83A336919B4A315CE0B-SPED-EFD.txt
Processando 27197888026036-107670534-20260401-20260430-0-BF8F95FD8010F9EACF1A09E3C00134839BEFF809-SPED-EFD.txt
Processando 27197888015506-9066079217-20260401-20260430-0-C888092A3329486A8F95405801505BB80BB41F55-SPED-EFD.txt
Processando 17625216001389-796186835115-20260401-20260430-0-896ADA4D18CEE5C42FDA9616EB968B4A8DD67FB0-SPED-EFD.txt
Processando 27197888025145-190925701-20260401-20260430-0-507D8D54984383A9118ACF3EEEADBBD645FAA1CB-SPED-EFD.txt
Processando 27197888023100-0628832431512-20260401-20260430-0-4A4057D48F296BA4B316CE44E39C50C0CB67C426-SPED-EFD.txt
Processando 27197888017983-0738333402423-20260401-20260430-0-6B999B7C51122F6DDFACC47B291130A3A8059C69-SPED-EFD.txt
Processando 27197888005462-116437255115-20260401-20260430-0-771D0089D32743A206FCC9F85308463C54ECD730-SPED-EFD.txt

# Verificação rápida

In [8]:
print("Empresas:", len(empresas))
print("CFOP Detalhado:", len(cfop_detalhado))
print("Apurações:", len(apuracoes))
print("Ajustes:", len(ajustes))
print("Obrigações:", len(obrigacoes))

Empresas: 187
CFOP Detalhado: 914671
Apurações: 187
Ajustes: 258
Obrigações: 138

# Conferência

In [9]:
pd.DataFrame(cfop_detalhado).head()

,RAIZ_CNPJ,CNPJ,IE,RAZAO_SOCIAL,UF,PERIODO,ARQUIVO,TIPO_OPERACAO,NUM_DOC,CHV_NFE,CST,CFOP,ALIQ_ICMS,VL_OPR,VL_BC_ICMS,VL_ICMS,VL_BC_ST,VL_ICMS_ST,VL_RED_BC
0,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013383,35260417625216000145550500000133831938850002,140,1152,0.0,24019.35,0.0,0.0,0.0,0.0,0.0
1,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013376,35260417625216000145550500000133761124554482,140,1152,0.0,230.67,0.0,0.0,0.0,0.0,0.0
2,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013389,35260417625216000145550500000133891568225293,140,1152,0.0,163.44,0.0,0.0,0.0,0.0,0.0
3,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013413,35260417625216000145550500000134131812939099,140,1152,0.0,301.86,0.0,0.0,0.0,0.0,0.0
4,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013450,35260417625216000145550500000134501844385475,140,1152,0.0,23417.57,0.0,0.0,0.0,0.0,0.0

# 7º Criação dos Dataframes

In [11]:
df_empresas = pd.DataFrame(empresas)
df_cfop = pd.DataFrame(cfop_detalhado)
df_apuracao = pd.DataFrame(apuracoes)
df_ajustes = pd.DataFrame(ajustes)
df_obrigacoes = pd.DataFrame(obrigacoes)

print("Empresas:", len(df_empresas))
print("CFOP:", len(df_cfop))
print("Apuração:", len(df_apuracao))
print("Ajustes:", len(df_ajustes))
print("Obrigações:", len(df_obrigacoes))

Empresas: 187
CFOP: 914671
Apuração: 187
Ajustes: 258
Obrigações: 138

# Teste

In [12]:
df_cfop.head()

,RAIZ_CNPJ,CNPJ,IE,RAZAO_SOCIAL,UF,PERIODO,ARQUIVO,TIPO_OPERACAO,NUM_DOC,CHV_NFE,CST,CFOP,ALIQ_ICMS,VL_OPR,VL_BC_ICMS,VL_ICMS,VL_BC_ST,VL_ICMS_ST,VL_RED_BC
0,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013383,35260417625216000145550500000133831938850002,140,1152,0.0,24019.35,0.0,0.0,0.0,0.0,0.0
1,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013376,35260417625216000145550500000133761124554482,140,1152,0.0,230.67,0.0,0.0,0.0,0.0,0.0
2,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013389,35260417625216000145550500000133891568225293,140,1152,0.0,163.44,0.0,0.0,0.0,0.0,0.0
3,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013413,35260417625216000145550500000134131812939099,140,1152,0.0,301.86,0.0,0.0,0.0,0.0,0.0
4,17625216,17625216001036,796186792116,DUFRY LOJAS FRANCAS LTDA,SP,2026-04,17625216001036-796186792116-20260401-20260430-...,Entrada Estadual,000013450,35260417625216000145550500000134501844385475,140,1152,0.0,23417.57,0.0,0.0,0.0,0.0,0.0

# 8º CFOP_RESUMIDO

In [13]:
df_cfop_resumido = (
    df_cfop
    .groupby(
        [
            "RAIZ_CNPJ",
            "CNPJ",
            "IE",
            "RAZAO_SOCIAL",
            "UF",
            "PERIODO",
            "CFOP",
            "CST",
            "ALIQ_ICMS"
        ],
        as_index=False
    )
    .agg(
        {
            "VL_OPR":"sum",
            "VL_BC_ICMS":"sum",
            "VL_ICMS":"sum",
            "VL_BC_ST":"sum",
            "VL_ICMS_ST":"sum",
            "VL_RED_BC":"sum"
        }
    )
)

# 9º RESUMO_EXECUTIVO

In [37]:
entradas = (
    df_cfop[
        df_cfop["CFOP"].astype(str).str.startswith(("1","2","3"))
    ]
    .groupby(["CNPJ","PERIODO"])["VL_OPR"]
    .sum()
    .reset_index()
    .rename(columns={"VL_OPR":"TOTAL_ENTRADAS"})
)

saidas = (
    df_cfop[
        df_cfop["CFOP"].astype(str).str.startswith(("5","6","7"))
    ]
    .groupby(["CNPJ","PERIODO"])["VL_OPR"]
    .sum()
    .reset_index()
    .rename(columns={"VL_OPR":"TOTAL_SAIDAS"})
)

resumo = df_empresas[
    [
        "RAIZ_CNPJ",
        "CNPJ",
        "IE",
        "RAZAO_SOCIAL",
        "UF",
        "PERIODO",
        "ARQUIVO"
    ]
].copy()

resumo = resumo.merge(
    entradas,
    on=["CNPJ","PERIODO"],
    how="left"
)

resumo = resumo.merge(
    saidas,
    on=["CNPJ","PERIODO"],
    how="left"
)

resumo["TOTAL_ENTRADAS"] = resumo["TOTAL_ENTRADAS"].fillna(0)
resumo["TOTAL_SAIDAS"] = resumo["TOTAL_SAIDAS"].fillna(0)

# 10º ICMS RECOLHER E FECP

In [38]:
icms_recolher = (
    df_apuracao[
        ["CNPJ","PERIODO","VL_ICMS_RECOLHER"]
    ]
)

resumo = resumo.merge(
    icms_recolher,
    on=["CNPJ","PERIODO"],
    how="left"
)

resumo["VL_ICMS_RECOLHER"] = resumo["VL_ICMS_RECOLHER"].fillna(0)

# ==========================================
# FECP (RJ)
# Utiliza apenas o ajuste RJ040010 para evitar duplicidade
# ==========================================

fecp = (
    df_ajustes[
        df_ajustes["COD_AJUSTE"] == "RJ040010"
    ]
    .groupby(
        ["CNPJ","PERIODO"]
    )["VALOR"]
    .sum()
    .reset_index()
    .rename(columns={"VALOR":"FECP"})
)

resumo = resumo.merge(
    fecp,
    on=["CNPJ","PERIODO"],
    how="left"
)

if "FECP" not in resumo.columns:
    resumo["FECP"] = 0

resumo["FECP"] = resumo["FECP"].fillna(0)

# 11º Exportar CSV Detalhado

In [39]:
df_cfop.to_csv(
    ARQUIVO_CFOP,
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print("CSV gerado.")

CSV gerado.

# 12º Exportar Excel

In [40]:
with pd.ExcelWriter(
    ARQUIVO_EXCEL,
    engine="xlsxwriter"
) as writer:

    df_empresas.to_excel(
        writer,
        sheet_name="EMPRESAS",
        index=False
    )

    df_cfop_resumido.to_excel(
        writer,
        sheet_name="CFOP_RESUMIDO",
        index=False
    )

    df_apuracao.to_excel(
        writer,
        sheet_name="APURACAO_ICMS",
        index=False
    )

    df_ajustes.to_excel(
        writer,
        sheet_name="AJUSTES_E111",
        index=False
    )

    df_obrigacoes.to_excel(
        writer,
        sheet_name="OBRIGACOES_E116",
        index=False
    )

    resumo.to_excel(
        writer,
        sheet_name="RESUMO_EXECUTIVO",
        index=False
    )

print("Excel gerado com sucesso.")
print(ARQUIVO_EXCEL)
print(ARQUIVO_CFOP)

Excel gerado com sucesso.
/content/SPED/RESULTADOS/Consolidado_SPED_20260609_162857.xlsx
/content/SPED/RESULTADOS/CFOP_DETALHADO_20260609_162857.csv